DAS_APP/urls.py
from django.contrib import admin
from django.urls import path
from DAS_APP import settings
from django.conf.urls import url, include
from django.contrib import admin
from core import views
# from django.views import static
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.login_page,name='login_page'),
    url(r'^logout/$', views.logout_page, name='logout_page'),
    url(r'^accueil/$', views.accueil, name='accueil'),
    url(r'^pdf/(?P<type>[a-z]{2})/(?P<val>[0-9]{0,9})/$', views.fleet_report_pdf, name='fleet_report_pdf'),

    # SERVICE MEDICAL URLS
    url(r'^accueil/addCharge/$', views.addCharge, name='addCharge'),
    url(r'^accueil/addOrdonnance/$', views.nouv_ordonnance, name='addOrdonnance'),
    url(r'^accueil/listeclinique/$', views.liste_clinique, name='liste_clinique'),
    url(r'^accueil/listePieces/$', views.liste_piece, name='liste_piece'),
    url(r'^accueil/ajouterclinique/$', views.ajouter_clinique, name='ajouter_clinique'),
    url(r'^accueil/ordonnance/$', views.nouv_ordonnance, name='nouv_ordonnance'),
    url(r'^accueil/info_charge/$', views.info_charge, name='info_charge'),
    url(r'^ajouterPieceCom/$', views.nouv_piece_compt, name='nouv_piece_compt'),
    url(r'^accueil/medicale/$', views.medicale_page, name='medicale_page'),
    url(r'^accueil/medicale/delete/(?P<type>[a-z]{2,3})/(?P<val>[0-9]{0,9})/$', views.delete, name='delete'),
    # SERVICE RETRAITE URLS
    url(r'^accueil/retraite/$', views.retraite_page, name='retraite_page'),
    url(r'^accueil/engagement/$', views.engagement, name='addEng'),
    url(r'^accueil/retraite/etat/$', views.addEtat, name='addEtat'),
    url(r'^accueil/retraite/add/$', views.addPele, name='addPele'),
    url(r'^accueil/retraite/search/(?P<par1>[a-z0-9]{5,9})/(?P<par2>[a-z])/$', views.search_emp, name='search_emp'),
    url(r'^teste/$', views.statistique, name='str'),

    # SERVICE SOCIAL URLS
    url(r'^accueil/sociale/$', views.action_page, name='action_page'),



    url(r'^accueil/search/$', views.search_page, name='search_page'),
    url(r'^accueil/loadpage/(?P<par1>[a-z0-9]{2,9})/$', views.loadpage, name='loadpage'),
    url(r'^accueil/service2/(?P<par1>[a-z0-9]{2,9})/(?P<par2>[a-z])/$', views.search_page, name='search_page'),
    url(r'^accueil/stats/(?P<varM>[a-z0-9]{1,9})/(?P<varA>[a-z0-9]{2,9})/(?P<MA>[a-z]{2,9})/$', views.stats_med, name='stats_med'),
    url(r'^accueil/pdf/$', views.pdf, name='pdf'),
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^explorer/', include('explorer.urls')),
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from ser_social.models import *
from django.contrib import admin

# Create your models here.


class Employe(models.Model):
    matricule = models.IntegerField(primary_key=True)
    cnam = models.IntegerField()
    nom_prenom = models.CharField(max_length=100)
    date_emb = models.DateTimeField(auto_now=False, auto_now_add=False)
    date_dep = models.DateTimeField(auto_now=False, auto_now_add=False)
    statut = models.CharField(max_length=10)
    civilite = models.CharField(max_length=5, default="Homme")

    def __str__(self):
        return self.nom_prenom


class InfoEmploye(models.Model):
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    pelerin = models.ForeignKey(Pelerinage, on_delete=models.CASCADE)
    somme = models.IntegerField()


class Gains(models.Model):
    date = models.DateTimeField(auto_now=False, auto_now_add=False)
    montant = models.IntegerField(null=True)
    libele_g = models.TextField(null=True)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)

ser_social/models.py
from django.db import models

# Create your models here.


class Pelerinage(models.Model):
    date_pel = models.DateField(auto_now=False, auto_now_add=False,blank=False)
    frais = models.IntegerField(null=True)

    def __str__(self):
        return self.date_pel

ser_social/forms.py
from django import forms
from django.forms.widgets import Input
from app import models
from django.forms import ModelChoiceField, ModelForm
from django.db import models as md

ser_social/views.py
from ser_medical.views import *
from ser_retraite.views import *
from ser_social.views import *
from core.views import *
from ser_social.models import *
from core.models import *
def action_page(request):
    pel=Pelerinage.objects.order_by('id')
    nbre=0
    somme=0
    i=0
    bar_chart = pygal.Histogram()
    bar_chart.x_labels='STATISTIQUE'
    for pe in pel:
        nbre = nbre+1
        somme = somme+pe.frais
        bar_chart.add(str(pe.date_pel.year), [(pe.frais, i, i+0.5)])
        i = i+0.5
    bar_chart.add('Total Frais', [(somme, i, i+0.5)])
    bar = bar_chart.render()
    # context = {'message': 'Hello Pygal!'}
    # return render(request, 'medical/statistique.html', {'bar_chart': bar})
    return render(request, 'ser_social/sociale_page.html',{'pels':pel, 'bar_chart': bar})

def addPele(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            date = request.POST.get('date')
            myfile = request.FILES['file']
            dt = date.split("-")
            print('la date du jour', dt[0])
            if existePel(int(dt[0])):
                return accueil(request)
            else:
                fs = FileSystemStorage()
                filename = fs.save(myfile.name, myfile)
                chemin = 'media/' + filename
                book = pyexcel.get_book(file_name=chemin)
                frais = 0
                peleringe = Pelerinage(date_pel=date)
                peleringe.save()
                for feuille in book:
                    # chaque feuille a un nom
                    print("feuille: %s" % feuille.name)

                    for ligne in feuille:
                        c1 = ligne[0]
                        c2 = ligne[2]
                        frais = c2+frais
                        emp = Employe.objects.get(matricule=c1)
                        ie = InfoEmploye(employe=emp, pelerin=peleringe, somme=c2)
                        ie.save()
                    peleringe.frais = frais
                    peleringe.save()

            return render(request, 'ser_medical/smedical.html')
        # elif request.is_ajax():
        #     errors = json.dumps(form.errors)
        #     return HttpResponse(errors)
        else:
            return render(request, 'ser_retraite/sretraite.html')
    else:
        form = UploadFileForm()
        return render(request, 'ser_social/nouv_pel.html', {'form':form})


def existePel(year):
    pels = Pelerinage.objects.all()
    for pel in pels:
        if (pel.date_pel.year == year):
            return True
    return False

ser_social/templates/ser_social/nouv_pel.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_social/js/ajoutP.js' %}" type="text/javascript"></script>
{% endblock %}
{% block stylesheet%}
	<link href="{% static 'ser_social/css/accueil.css'%}" rel="stylesheet" type="text/css">
	<link href="{% static 'ser_social/css/recherche.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

<div class="panel-heading">
    <span class="pan_title">Nouveau Pelerinage</span>
    <button type="button" class="close" id="close">×</button>
</div>
<form id="npel_id" action="{% url 'addPele' %}" method="post" class="niceform panel-body well" novalidate enctype="multipart/form-data">{% csrf_token %}
        <fieldset >

            <div class="col-sm-9">
            <dl class="dl-horizontal">
                <dt>DATE</dt>
                <dd><input id="id_date" min="0" name="date" type="DATE" required=""></dd>
                <dd><span id="errp"></span></dd>
            </dl>
            <dl class="dl-horizontal">
                <dd>{{ form.file}}</dd>
                <dd>{{ form.file.errors }}</dd>
            </dl>

            <div >
                <input class="btn btn-success col-sm-offset-2" type="submit" value="valider" id="valEng" />
            </div>
                </div>
        </fieldset>

</form>

ser_social/templates/ser_social/sociale_page.html
{% extends "base.html" %}
{% load static %}

{% block JheadScript %}
    <script src="{% static 'ser_social/js/listpel.js' %}" type="text/javascript"></script>

    <script src="{% static 'ser_social/js/sociale.js' %}" type="text/javascript"></script>
{% endblock %}

{% block stylesheet%}
	<link href="{% static 'core/css/accueil.css'%}" rel="stylesheet" type="text/css">
	<link href="{% static 'core/css/recherche.css'%}" rel="stylesheet" type="text/css">
{% endblock %}


{% block service%}SERVICE ACTION SOCIALE{% endblock %}

{% block content%}

{% if user.is_authenticated %}
    <div class="container bdSocial ">
		<div class="row">
            <div>
                <a href="{% url 'accueil'%}" id="home" class="pan_title2 active">
                <img width="50" height="35" src="{% static 'core/images/home.ico'%}">
            </a>
            </div>

			<div class=" col-sm-6 panel panel-default">
			<table id="lprise" class=" well table table-striped table-hover table-bordered dt-responsive nowrap" cellspacing="0" width="100px">
        	<caption>
				<span class="pan_title">PELERINAGES</span>
				<button id="ajpeler_id" type="button" class="col-sm-offset-3 btn btn-well" >ajouter</button>
			</caption>
                {% if pels%}

            <thead>
                <tr class=" col-lg-1">
                    <th>PELERINAGE N°</th>
                    <th>DATE</th>
                    <th>TOTAL FRAIS</th>
                </tr>
            </thead>
        	{%endif%}
        	<tbody>
            {% for pel in pels%}
            <tr>
                <td width="10%">{{pel.id}}</td>
                <td width="10%">{{pel.date_pel}}</td>
                <td width="15%">{{pel.frais}}</td>
                <td width="5%"><a href="#" data-toggle="modal" title="fiche circulation prise en charge" class="icon-1" data-target="#_{{piece.id}}_p1" ></a></td>
            </tr>


            {% empty %}
            AUCUN PELERINAGE ENREGISTRE
            {% endfor %}
        	</tbody>
    		</table>
			<div class="col-lg-offset-3" id="page_navigationP"> </div>
			<div class="panel panel-heading" id="socontonie"></div>
		</div>
		<div class="col-sm-6">{{bar_chart|safe}}</div>
		</div>

	</div>

{% endif %}
{% endblock %}