DAS_APP/urls.py
from django.contrib import admin
from django.urls import path
from DAS_APP import settings
from django.conf.urls import url, include
from django.contrib import admin
from core import views
# from django.views import static
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.login_page,name='login_page'),
    url(r'^logout/$', views.logout_page, name='logout_page'),
    url(r'^accueil/$', views.accueil, name='accueil'),
    url(r'^pdf/(?P<type>[a-z]{2})/(?P<val>[0-9]{0,9})/$', views.fleet_report_pdf, name='fleet_report_pdf'),

    # SERVICE MEDICAL URLS
    url(r'^accueil/addCharge/$', views.addCharge, name='addCharge'),
    url(r'^accueil/addOrdonnance/$', views.nouv_ordonnance, name='addOrdonnance'),
    url(r'^accueil/listeclinique/$', views.liste_clinique, name='liste_clinique'),
    url(r'^accueil/listePieces/$', views.liste_piece, name='liste_piece'),
    url(r'^accueil/ajouterclinique/$', views.ajouter_clinique, name='ajouter_clinique'),
    url(r'^accueil/ordonnance/$', views.nouv_ordonnance, name='nouv_ordonnance'),
    url(r'^accueil/info_charge/$', views.info_charge, name='info_charge'),
    url(r'^ajouterPieceCom/$', views.nouv_piece_compt, name='nouv_piece_compt'),
    url(r'^accueil/medicale/$', views.medicale_page, name='medicale_page'),
    url(r'^accueil/medicale/delete/(?P<type>[a-z]{2,3})/(?P<val>[0-9]{0,9})/$', views.delete, name='delete'),
    # SERVICE RETRAITE URLS
    url(r'^accueil/retraite/$', views.retraite_page, name='retraite_page'),
    url(r'^accueil/engagement/$', views.engagement, name='addEng'),
    url(r'^accueil/retraite/etat/$', views.addEtat, name='addEtat'),
    url(r'^accueil/retraite/add/$', views.addPele, name='addPele'),
    url(r'^accueil/retraite/search/(?P<par1>[a-z0-9]{5,9})/(?P<par2>[a-z])/$', views.search_emp, name='search_emp'),
    url(r'^teste/$', views.statistique, name='str'),

    # SERVICE SOCIAL URLS
    url(r'^accueil/sociale/$', views.action_page, name='action_page'),



    url(r'^accueil/search/$', views.search_page, name='search_page'),
    url(r'^accueil/loadpage/(?P<par1>[a-z0-9]{2,9})/$', views.loadpage, name='loadpage'),
    url(r'^accueil/service2/(?P<par1>[a-z0-9]{2,9})/(?P<par2>[a-z])/$', views.search_page, name='search_page'),
    url(r'^accueil/stats/(?P<varM>[a-z0-9]{1,9})/(?P<varA>[a-z0-9]{2,9})/(?P<MA>[a-z]{2,9})/$', views.stats_med, name='stats_med'),
    url(r'^accueil/pdf/$', views.pdf, name='pdf'),
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^explorer/', include('explorer.urls')),
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from ser_social.models import *
from django.contrib import admin

# Create your models here.


class Employe(models.Model):
    matricule = models.IntegerField(primary_key=True)
    cnam = models.IntegerField()
    nom_prenom = models.CharField(max_length=100)
    date_emb = models.DateTimeField(auto_now=False, auto_now_add=False)
    date_dep = models.DateTimeField(auto_now=False, auto_now_add=False)
    statut = models.CharField(max_length=10)
    civilite = models.CharField(max_length=5, default="Homme")

    def __str__(self):
        return self.nom_prenom


class InfoEmploye(models.Model):
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    pelerin = models.ForeignKey(Pelerinage, on_delete=models.CASCADE)
    somme = models.IntegerField()


class Gains(models.Model):
    date = models.DateTimeField(auto_now=False, auto_now_add=False)
    montant = models.IntegerField(null=True)
    libele_g = models.TextField(null=True)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)

ser_retraite/models.py
from django.db import models
from core.models import *

# Create your models here.


class Engagement(models.Model):
    date_en = models.DateField(auto_now=False, auto_now_add=False,blank=False)
    montant = models.IntegerField(null=True)
    motif = models.TextField(null=True)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    type = models.ForeignKey('TypeEng', on_delete=models.CASCADE)


class TypeEng(models.Model):
    libele = models.CharField(max_length=50)

    def __str__(self):
        return self.libele


class TypeEngAdmin(admin.ModelAdmin):
    search_fields = ['libele']

class EngagementAdmin(admin.ModelAdmin):
    search_fields = ['montant']
# admin.site.register(Employe, EmployeAdmin)
admin.site.register(TypeEng, TypeEngAdmin)
admin.site.register(Engagement, EngagementAdmin)

ser_retraite/forms.py
from django import forms
from django.forms.widgets import Input
from ser_retraite import models
from django.forms import ModelChoiceField, ModelForm
from django.db import models as md

class Html5EmailInput(Input):
    input_type = 'email'

class UploadFileForm(forms.Form):
    file = forms.FileField()





class EngagementForm(ModelForm):

    class Meta:
        model = models.Engagement
        exclude = ('employe','date_en',)
        widgets = {
            # 'date_en':forms.DateInput(attrs={'class': 'datepicker'}),
            'motif': forms.Textarea(attrs={'cols': 22, 'rows': 2}),

        }

ser_retraite/views.py
from ser_medical.views import *
from ser_retraite.views import *
from ser_social.views import *
from ser_medical.forms import SoinForm,\
    CliniqueForm, PieceComForm, OrdonnanceForm, UploadFileForm, StatsForm
from ser_retraite.forms import EngagementForm
from core import models
from ser_retraite import models as mr

def retraite_page(request):
    return render(request, 'ser_retraite/sretraite.html')


def engagement(request):
    if request.method == 'POST':
        form = EngagementForm(request.POST)
        if form.is_valid():
            matricule = request.POST.get('matricule')
            date = request.POST.get('date_en')

            eng = form.save(commit=False)
            eng.employe = models.Employe.objects.get(matricule=matricule)
            eng.date_en = date
            eng.save()
            if request.is_ajax():
                return HttpResponse(content=json.dumps({'success': '/success'}))
        elif request.is_ajax():
            errors = json.dumps(form.errors)
            return HttpResponse(errors)
    else:
        form = EngagementForm()
        return render(request,'ser_retraite/engagement.html',{'form': form})


def liste_engagement(request):
    engs = mr.Engagement.objects.order_by('-date_en')
    return render(request, 'ser_retraite/ListeEngagement.html', {'engs': engs})


def search_emp(request, par1,par2):
    try:
        emp = models.Employe.objects.get(matricule=par1)
        # eng = models.Engagement.objects(employe = emp)
        statut = "success1"
    except:
        statut = "error1"
        emp = par1
    if par2 == 'a':
        return render(request, 'ser_retraite/info_emp.html', {'text': emp, 'statut': statut, })
    if par2 == 'b':
        engs = mr.Engagement.objects.filter(employe=emp)
        form = EngagementForm()
        return render(request, 'ser_retraite/info_emp.html', {'engs': engs, 'cat': '3', 'form':form})

ser_retraite/templates/ser_retraite/ListeEngagement.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_retraite/js/listeEng.js' %}" type="text/javascript"></script>
{% endblock %}
<div class="well">
    <table  class="table table-striped table-hover table-condensed table-bordered">
        {% if engs%}
            <caption>
                <span class="pan_title">Liste des Engagements</span>
                <button id="ajEng_id" type="button" class="col-sm-offset-7 btn btn-well" >ajouter</button>
            </caption>
            <thead>
                <tr class=" col-lg-1">

                    <th>DATE</th>
                    <th>MONTANT</th>
                    <th>ASSURE</th>
                    <th>MOTIF</th>
                    <th>TYPE</th>

                </tr>
            </thead>
        {%endif%}
        <tbody id="tbEn">
            {% for eng in engs %}
            <tr>
                <td >{{eng.date_en}}</td>
                <td >{{eng.montant}}</td>
                <td >{{eng.employe}}</td>
                <td >{{eng.motif}}</td>
                <td >{{eng.type}}</td>
                <td><a href="#" data-toggle="tooltip" title="Editer" class="icon-1" ></a></td>
            </tr>
            {% empty %}
            <tr>
                <td>PAS D'ENGAGEMENT ENREGISTRER</td>
                <td><button id="ajEng_id2" type="button" class="col-sm-offset-7 btn btn-well" >ajouter</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="col-sm-offset-3" id="page_navigation4"> </div>
</div>

ser_retraite/templates/ser_retraite/allocation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

ser_retraite/templates/ser_retraite/engagement.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_retraite/js/engform.js' %}" type="text/javascript"></script>
{% endblock %}
{% block stylesheet%}
	<link href="{% static 'core/css/accueil.css'%}" rel="stylesheet" type="text/css">
	<link href="{% static 'core/css/recherche.css'%}" rel="stylesheet" type="text/css">
{% endblock %}
<script>
        $(function() {
            $( "#id_date_en" ).datepicker();});

        </script>
<div class="panel-heading">
    <span class="pan_title">Nouvel Engagement</span>
    <button type="button" class="col-sm-offset-5 close" id="close">×</button>
</div>
<form id="engFor_id" action="{% url 'addEng' %}" method="post" class="niceform panel-body well" novalidate enctype="multipart/form-data">{% csrf_token %}
        <fieldset >

            <div class="col-sm-9">
            <dl class="dl-horizontal">
                <dt>DATE</dt>
                <dd><input id="id_date_en" min="0" name="date_en" type="DATE" required=""></dd>
                <dd></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>MONTANT</dt>
                <dd>{{ form.montant}}</dd>
                <dd>{{ form.montant.errors }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Matricule</dt>
                <dd><input id="id_matricule" min="0" name="matricule" type="number" required=""></dd>
                <dd></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>MOTIF</dt>
                <dd>{{ form.motif }}</dd>
                <dd>{{ form.motif.errors }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>TYPE</dt>
                <dd>{{ form.type }}</dd>
                <dd>{{ form.type.errors }}</dd>
            </dl>
            <div class="row">&nbsp;
            </div>
            <div >
                <input class="btn btn-danger   col-sm-offset-3" type="reset" value="annuler" id="annEng">
                <input class="btn btn-success " type="submit" value="valider" id="valEng" />
            </div>
                </div>
            <div class="col-sm-5"><section id="employe"></section></div>
        </fieldset>

</form>

ser_retraite/templates/ser_retraite/engagement_dial.html
<table id="lprise" class="table table-striped table-hover table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                        {% if eng%}
                            <caption><span class="pan_title">Engagement</span></caption>
                            <thead>
                                <tr class=" col-lg-1">
                                    <th>DATE</th>
                                    <th>MONTANT</th>
                                    <th>MOTIF</th>
                                    <th>TYPE</th>
                                </tr>
                            </thead>
                        {%endif%}
                        <tbody>
                            {% for eng in eng %}
                            <tr>
                                <td >{{eng.date_en}}</td>
                                <td >{{eng.montant}}</td>
                                <td>{{eng.motif}}</td>
                                <td >{{eng.type}}</td>
                                <td><a href="#" data-toggle="modal" title="fiche circulation prise en charge" class="icon-1" data-target="#_{{piece.id}}_p1" ></a></td>
                                <td><a href="#" data-toggle="modal" title="Prise en charge" class="icon-1" data-target="#_{{piece.id}}_p2" ></a></td>

                            </tr>
                            <div id="_{{piece.id}}_p1" class="modal" role="dialog" aria-labelledby="_{{piece.id}}_title1" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" data-dismiss="modal" class="close" aria-hidden="true">&times;</button>
                                            <span class="pan_title" id="_{{piece.id}}_title1">Fiche de Circulation Prise en Charge</span>
                                        </div>
                                        <div class="modal-body"></div>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <tr><td>PAS D'AVANCE IDR PRISE</td></tr>
                            {% endfor %}
                        </tbody>
                    </table>

ser_retraite/templates/ser_retraite/etat.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'js/retraite/engform.js' %}" type="text/javascript"></script>
{% endblock %}
{% block stylesheet%}
	<link href="{% static 'css/accueil.css'%}" rel="stylesheet" type="text/css">
	<link href="{% static 'css/recherche.css'%}" rel="stylesheet" type="text/css">
{% endblock %}

<div class="panel-heading">
    <span class="pan_title">Nouvel Etat</span>
    <button type="button" class="col-sm-offset-5 close" id="close">×</button>
</div>
<form id="etat_id" action="{% url 'addEtat' %}" method="post" class="niceform panel-body well" novalidate enctype="multipart/form-data">{% csrf_token %}
        <fieldset >

            <div class="col-sm-9">
            <dl class="dl-horizontal">
                <dt>DATE</dt>
                <dd><input id="id_date_en" min="0" name="date" type="DATE" required=""></dd>
                <dd></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Choisir un fichier</dt>
                <dd>{{ form.file}}</dd>
                <dd>{{ form.file.errors }}</dd>
            </dl>

            <div >
                <input class="btn btn-success " type="submit" value="valider" id="valEng" />
            </div>
                </div>
        </fieldset>

</form>

ser_retraite/templates/ser_retraite/info_emp.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_retraite/js/sretraite.js' %}" type="text/javascript"></script>
    <script src="{% static 'ser_retraite/js/listeEng.js' %}" type="text/javascript"></script>
    <script src="{% static 'ser_retraite/js/engform.js' %}" type="text/javascript"></script>

{% endblock %}
{% if statut == "error1"%}
    <div class="col-sm-offset-1 col-sm-7 alert alert-danger alert-dismissable">
        <button data-dismiss="alert" type="button" class="close">&times;</button>
        <strong>Aucun d'employe enregistre sur ce matricule {{texte}}!</strong>
    </div>
{% endif %}
{%if statut == "success1"%}
    <div class="col-sm-4 panel panel-default">
        <table>
            <tbody>
                <tr>
                    <td rowspan="5"><img class="img-circle" width="100" height="135" src="{% static 'core/images/mine/fpv.jpeg' %}"></td>
                    <td  id="{{text.matricule}}" class="matricule_ids">Matricule:<span class="label label-success">{{text.matricule}}</span></td>
                </tr>
                <tr>
                    <td>Cnam:<span class="label label-success">{{text.cnam}}</span></td>
                </tr>
                <tr>
                    <td>Nom & Prenom:<span class="label label-success">{{text.nom_prenom}}</span></td>
                </tr>
                <tr>
                    <td>service depuis:<span class="label label-success">{{text.date_emb.date}}</span></td>
                </tr>
                <tr>
                    <td>Statut:<span class="label label-success">{{text.statut}}</span></td>
                </tr>
            </tbody>
        </table>
        <div class=" panel panel-default">
            <dl>
                <dd><a href="#" class="" id="dretraite">droit retraite</a></dd>
                <dd ><img width="120" height="4" src="{% static 'core/images/diviseurH.gif' %}"></dd>
                <dd><a href="#" class="">allocation familialle</a>
                <dd ><img width="120" height="4" src="{% static 'core/images/diviseurH.gif' %}"></dd>
                <dd><a href="#" id="engIdretraite">engagement</a></dd>
            </dl>
        </div>
    </div>

    <div class="col-sm-8" id="opt"></div>
{% endif %}
{% if cat == "3" %}

<div class="row">
 <table id="lprise" class="col-sm-1 table table-striped table-hover table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
    {% if engs%}
    <caption>
        <span class="pan_title">Engagement</span>
        <button type="button" data-toggle="modal" data-target="#addEn"  class="col-sm-offset-3 btn btn-well" href="#">ajouter</button>
    </caption>
    <thead>
        <tr class=" col-lg-1">
            <th>DATE</th>
            <th>MONTANT</th>
            <th>MOTIF</th>
            <th>TYPE</th>
        </tr>
    </thead>
    {%endif%}
    <tbody id="tbEn">
        {% for eng in engs %}
        <tr>
            <td >{{eng.date_en}}</td>
            <td >{{eng.montant}}</td>
            <td>{{eng.motif}}</td>
            <td >{{eng.type}}</td>
        </tr>


        {% empty %}
        <tr>
            <td><span>AUCUNE AVANCE IDR PRISE</span></td>
            <td><button type="button" data-toggle="modal" data-target="#addEn"  class="col-sm-offset-3 btn btn-well" href="#">ajouter</button>
</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

    <dl class="dl-horizontal">
        <dd class="col-lg-offset-3" id="page_navigation4"> </dd>
    </dl>
</div>
<div id="addEn" class="modal" role="dialog" aria-labelledby="addEng_title" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" data-dismiss="modal" class="close" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                {% include "ser_retraite/engagement.html" with form=form %}
            </div>
        </div>
    </div>
</div>
{% endif %}

ser_retraite/templates/ser_retraite/sretraite.html
{% extends "base.html" %}
{% load static %}

{% block JheadScript %}
    <script src="{% static 'ser_retraite/js/sretraite.js' %}" type="text/javascript"></script>
{% endblock %}

{% block stylesheet%}
	<link href="{% static 'ser_retraite/css/accueil.css'%}" rel="stylesheet" type="text/css">
	<link href="{% static 'ser_retraite/css/recherche.css'%}" rel="stylesheet" type="text/css">
{% endblock %}


{% block service%}SERVICE RETRAITE{% endblock %}

{% block content%}

{% if user.is_authenticated %}
    <div class="container">
		<div class=" row">
			<ul  class="nav nav-tabs panel panel-default  col-sm-10">
				<li ><a href="{% url 'accueil'%}" class="pan_title2 active"><img width="50" height="35" src="{% static 'core/images/home.ico'%}"></a></li>
				<li ><img width="2" height="40" src="{% static 'core/images/shared/nav/divider.jpg' %}"></li>
				<li ><a href="#" id="stats" page="retcontent" class="pan_title2 active">Stats</a></li>
				<li ><img width="2" height="40" src="{% static 'core/images/shared/nav/divider.jpg' %}"></li>
				<li ><a href="#" id="af" class="pan_title2 active">Allocation</a></li>
				<li ><img width="2" height="40" src="{% static 'core/images/shared/nav/divider.jpg' %}"></li>
				<li class="dropdown">
					<a href="#piece" class="dropdown-toggle pan_title2" data-toggle="dropdown">Droits<span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="#" id="lpcm" class="pan_title2">Maternite</a></li>
						<li class="divider"></li>
						<li><a href="#" id="pcm" class="pan_title2">Retraite</a></li>
					</ul>
				</li>
				<li ><img width="2" height="40" src="{% static 'core/images/shared/nav/divider.jpg' %}"></li>
				<li ><a href="#engagement" id="eng" class="pan_title2 active">Engagements</a></li>
				<li ><img width="2" height="40" src="{% static 'core/images/shared/nav/divider.jpg' %}"></li>
				<li>
					<form class="form">
						<div class="recherche">
							<input id="cherche_id" name="q" placeholder="Rechercher" type="search"/>
							<button id="search_sub" type="submit">ok</button>
						</div>
					</form>
				</li>
			</ul>
		</div>
		<div  id="retcontent" class="panel panel-default"></div>
	</div>

{% endif %}
{% endblock %}