DAS_APP/urls.py
from django.contrib import admin
from django.urls import path
from DAS_APP import settings
from django.conf.urls import url, include
from django.contrib import admin
from core import views
# from django.views import static
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.login_page,name='login_page'),
    url(r'^logout/$', views.logout_page, name='logout_page'),
    url(r'^accueil/$', views.accueil, name='accueil'),
    url(r'^pdf/(?P<type>[a-z]{2})/(?P<val>[0-9]{0,9})/$', views.fleet_report_pdf, name='fleet_report_pdf'),

    # SERVICE MEDICAL URLS
    url(r'^accueil/addCharge/$', views.addCharge, name='addCharge'),
    url(r'^accueil/addOrdonnance/$', views.nouv_ordonnance, name='addOrdonnance'),
    url(r'^accueil/listeclinique/$', views.liste_clinique, name='liste_clinique'),
    url(r'^accueil/listePieces/$', views.liste_piece, name='liste_piece'),
    url(r'^accueil/ajouterclinique/$', views.ajouter_clinique, name='ajouter_clinique'),
    url(r'^accueil/ordonnance/$', views.nouv_ordonnance, name='nouv_ordonnance'),
    url(r'^accueil/info_charge/$', views.info_charge, name='info_charge'),
    url(r'^ajouterPieceCom/$', views.nouv_piece_compt, name='nouv_piece_compt'),
    url(r'^accueil/medicale/$', views.medicale_page, name='medicale_page'),
    url(r'^accueil/medicale/delete/(?P<type>[a-z]{2,3})/(?P<val>[0-9]{0,9})/$', views.delete, name='delete'),
    # SERVICE RETRAITE URLS
    url(r'^accueil/retraite/$', views.retraite_page, name='retraite_page'),
    url(r'^accueil/engagement/$', views.engagement, name='addEng'),
    url(r'^accueil/retraite/etat/$', views.addEtat, name='addEtat'),
    url(r'^accueil/retraite/add/$', views.addPele, name='addPele'),
    url(r'^accueil/retraite/search/(?P<par1>[a-z0-9]{5,9})/(?P<par2>[a-z])/$', views.search_emp, name='search_emp'),
    url(r'^teste/$', views.statistique, name='str'),

    # SERVICE SOCIAL URLS
    url(r'^accueil/sociale/$', views.action_page, name='action_page'),



    url(r'^accueil/search/$', views.search_page, name='search_page'),
    url(r'^accueil/loadpage/(?P<par1>[a-z0-9]{2,9})/$', views.loadpage, name='loadpage'),
    url(r'^accueil/service2/(?P<par1>[a-z0-9]{2,9})/(?P<par2>[a-z])/$', views.search_page, name='search_page'),
    url(r'^accueil/stats/(?P<varM>[a-z0-9]{1,9})/(?P<varA>[a-z0-9]{2,9})/(?P<MA>[a-z]{2,9})/$', views.stats_med, name='stats_med'),
    url(r'^accueil/pdf/$', views.pdf, name='pdf'),
    #url(r'^admin/', include(admin.site.urls)),
    #url(r'^explorer/', include('explorer.urls')),
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ser_medical/models.py
from django.db import models
from django.contrib import admin
from core.models import Employe
from import_export.admin import ImportExportModelAdmin
# Create your models here.

SENS_CHOICES = (
            ('', '----------------'),
            ('C', 'C'),
            ('D', 'D'),
        )
TYPE_CLI_CHOICES = (
            ('', '----------------'),
            ('Local', 'Local'),
            ('Etranger', 'Etranger'),
        )
TYPE_ORD_CHOICES = (
            ('', '----------------'),
            ('0', 'Lunette'),
            ('1', 'Dent'),
        )
EMETTEUR_CHOICES = (
            ('', '----------------'),
            ('Service Action Sociale', 'Service Action Sociale'),
            ('Service Medical', 'Service Medical'),
            ('Service Retraite', 'Service Retraite'),
        )

AVIS_CHOICES = (
        ('', '----------------'),
        ('defavorable', 'defavorable'),
        ('favorable', 'favorable'),
    )


class Droits(models.Model):
    date_rec = models.DateTimeField(auto_now=False, auto_now_add=False)
    montant = models.IntegerField(null=True)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    type = models.ForeignKey('TypeDroit', on_delete=models.CASCADE)


class Ordonnances(models.Model):
    reference = models.IntegerField(primary_key=True)
    date_soum = models.DateTimeField(auto_now=True, auto_now_add=False)
    montant = models.IntegerField(null=True)
    employe = models.ForeignKey(Employe, on_delete=models.CASCADE)
    montant_rem = models.IntegerField()
    type = models.CharField(max_length=20, choices=TYPE_ORD_CHOICES)

    def __str__(self):
        return self.reference


class Clinique(models.Model):
    code = models.CharField(max_length=6, primary_key=True)
    libele = models.CharField(max_length=20)
    pays = models.CharField(max_length=20)
    type = models.CharField(max_length=20, choices=TYPE_CLI_CHOICES)
    # type = models.ForeignKey('TypeClinique', on_delete=models.CASCADE)
    def __str__(self):
        return self.libele


class Soins(models.Model):
    Nom_prenom = models.CharField(max_length=100)
    id_patient = models.CharField(max_length=30)
    description = models.TextField(null=True)
    Matricule = models.ForeignKey(Employe, on_delete=models.CASCADE)
    clinique = models.ForeignKey(Clinique, on_delete=models.CASCADE)
    date_soin = models.DateTimeField(auto_now=True, auto_now_add=False)
    chef_sec = models.CharField(max_length=100, choices=AVIS_CHOICES, null=True)
    chef_serv = models.CharField(max_length=100, choices=AVIS_CHOICES, null=True)
    dir = models.CharField(max_length=100, choices=AVIS_CHOICES, null=True)


class AyDroits(models.Model):
    nom_prenom = models.CharField(max_length=30)
    statut = models.CharField(max_length=10)
    date_de_naiss = models.DateTimeField(auto_now=False, auto_now_add=False)

    def __str__(self):
        return self.nom_prenom


class TypeDroit(models.Model):
    libele = models.CharField(max_length=50)

    def __str__(self):
        return self.libele


class TypeSoins(models.Model):
    libele = models.CharField(max_length=50)

    def __str__(self):
        return self.libele


class TypeClinique(models.Model):
    libele = models.CharField(max_length=50)

    def __str__(self):
        return self.libele


class PieceComptable(models.Model):
    emetteur = models.CharField(max_length=100, choices=EMETTEUR_CHOICES)
    objet = models.CharField(max_length=100)
    date_p = models.DateTimeField(auto_now=True)
    compte = models.IntegerField()
    intitule = models.TextField()
    libele = models.TextField()
    montant = models.IntegerField()
    sens = models.CharField(max_length=1, null=False, choices=SENS_CHOICES)
    beneficiaire = models.ForeignKey(Employe, on_delete=models.CASCADE)


class CliniqueAdmin(admin.ModelAdmin):
    search_fields = ['code']
admin.site.register(Clinique, CliniqueAdmin)

ser_medical/forms.py
from django import forms
from django.forms.widgets import Input
from ser_medical import models
from django.forms import ModelChoiceField, ModelForm
from django.db import models as md

MOIS_CHOICES = (
    ('1', 'Janvier'),
    ('2', 'Fevrier'),
    ('3', 'Mars'),
    ('4', 'Avril'),
    ('5', 'Mai'),
    ('6', 'Juin'),
    ('7', 'Juillet'),
    ('8', 'Aout'),
    ('9', 'Septembre'),
    ('10', 'Octobre'),
    ('11', 'Novembre'),
    ('12', 'Decembre'),
)

ASSURE_CHOICES = (
        ('', '----------------'),
        ('0', 'Principale'),
        ('1', 'Famille'),
    )


class Html5EmailInput(Input):
    input_type = 'email'

class UploadFileForm(forms.Form):
    file = forms.FileField()




class SoinForm(ModelForm):

    matricule=forms.IntegerField()
    class Meta:
        model = models.Soins
        exclude = ('Matricule','chef_sec','chef_serv','dir')
        widgets = {
            'description': forms.Textarea(attrs={'cols': 20, 'rows': 2}),
        }

    def __init__(self, *args, **kwargs):
        super(SoinForm, self).__init__(*args, **kwargs)
        self.fields['clinique'] = ModelChoiceField(queryset=models.Clinique.objects.all(),empty_label = "selectionner clini")

class CliniqueForm(ModelForm):
    class Meta:
        model = models.Clinique
        fields = '__all__'
    def __init__(self, *args, **kwargs):
        super(CliniqueForm, self).__init__(*args, **kwargs)
        # self.fields['type'] = ModelChoiceField(queryset=models.TypeClinique.objects.all(),empty_label = "selectionner type")


class PieceComForm(ModelForm):
    class Meta:

        model = models.PieceComptable
        exclude = ('beneficiaire',)
        widgets = {
            'intitule': forms.Textarea(attrs={'cols': 22, 'rows': 2}),
            'libele': forms.Textarea(attrs={'cols': 22, 'rows': 2}),
        }


class OrdonnanceForm(ModelForm):


    assure=forms.ChoiceField(choices=ASSURE_CHOICES)
    class Meta:
        model = models.Ordonnances
        # fields = '__all__'
        exclude = ('montant_rem','employe',)

    def __init__(self, *args, **kwargs):
        super(OrdonnanceForm, self).__init__(*args, **kwargs)
        # self.fields['type'] = ModelChoiceField(queryset=models.TypeClinique.objects.all(),empty_label = "selectionner type")



class StatsForm(forms.Form):
    mois = forms.ChoiceField(choices=MOIS_CHOICES,disabled=True)
    annee = forms.IntegerField(disabled=True)

ser_medical/templates/ser_medical/ajouterClinique.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_medical/js/ajoutClinik.js' %}" type="text/javascript"></script>
{% endblock %}
<form id="ajclForm" action="{% url 'ajouter_clinique' %}" method="post" class="niceform" novalidate enctype="multipart/form-data">{% csrf_token %}
    <fieldset id="" class="ctn1">
        <legend class="ctn1">Nouvelle Clinique</legend>
        <div class="row col-lg-11"> <dl class="dl-horizontal">
            <dt>{{ form.code.label_tag }}</dt>
            <dd>{{ form.code }}</dd>
            <dd>{{ form.code.errors }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>{{ form.libele.label_tag }}</dt>
            <dd>{{ form.libele }}</dd>
            <dd>{{ form.libele.errors }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>{{ form.pays.label_tag }}</dt>
            <dd>{{ form.pays }}</dd>
            <dd>{{ form.pays.errors }}</dd>
        </dl>
        <dl class="dl-horizontal">
            <dt>{{ form.type.label_tag }}</dt>
            <dd>{{ form.type }}</dd>
            <dd>{{ form.type.errors }}</dd>
        </dl></div>

            <input class="row  col-sm-offset-3 col-sm-2 btn btn-success" type="submit" value="Submit" />

    </fieldset>

</form>

ser_medical/templates/ser_medical/ajouter_pCompt.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_medical/js/pCompt.js' %}" type="text/javascript"></script>
{% endblock %}
<div class="panel-heading" id="pan_title">Nouvelle Piece Comptable</div>
<form id="pC_id" action="{% url 'nouv_piece_compt' %}" method="post" class="niceform panel-body" novalidate enctype="multipart/form-data">{% csrf_token %}
    <fieldset class="well">
        <legend></legend>
        <div class="col-sm-5">
            <dl>
                <dt>{{ form.emetteur.label_tag }}</dt>
                <dd>{{ form.emetteur }}</dd>
                <dd>{{ form.emetteur.errors }}</dd>
            </dl>
            <dl>
                <dt>{{ form.objet.label_tag }}</dt>
                <dd>{{ form.objet }}</dd>
                <dd>{{ form.objet.errors }}</dd>
            </dl>
            <dl>
                <dt>{{ form.compte.label_tag }}</dt>
                <dd>{{ form.compte }}</dd>
                <dd>{{ form.compte.errors }}</dd>
            </dl>
            <dl>
                <dt>{{ form.intitule.label_tag }}</dt>
                <dd>{{ form.intitule }}</dd>
                <dd>{{ form.intitule.errors }}</dd>
            </dl>
        </div>
        <div class="col-sm-6">
            <dl>
                <dt>{{ form.libele.label_tag }}</dt>
                <dd>{{ form.libele }}</dd>
                <dd>{{ form.libele.errors }}</dd>
            </dl>
            <dl>
                <dt>{{ form.montant.label_tag }}</dt>
                <dd>{{ form.montant }}<img class="img-circle" width="30" height="30" src="{% static 'ser_medical/images/ouguiya.png'%}"></dd>
                <dd>{{ form.montant.errors }}</dd>
            </dl>
            <dl>
                <dt>Matricule</dt>
                <dd><input id="id_matricule" min="0" name="matricule" type="number" required=""></dd>
                <dd></dd>
            </dl>
            <dl>
                <dt>{{ form.sens.label_tag }}</dt>
                <dd>{{ form.sens }}</dd>
                <dd>{{ form.sens.errors }}</dd>
            </dl>
            </div>
            <div class="col-sm-1">
                <input class="btn btn-success circle" type="submit" value="Valider" />
            </div>

        <div class="row col-sm-5"><section id="employeb"></section></div>
    </fieldset>

</form>

ser_medical/templates/ser_medical/fiche_circulaire.html
<style>
    body {
      background-color: #f7f7f7;
    }
    .ctnu{
        margin-left:20px;
    }
    .dl-horizontal dd {
        margin-left: 180px;
    }
    .dl-horizontal dt {
        float: left;
        width: 160px;
        overflow: hidden;
        clear: left;
        text-align: right;
        text-overflow: ellipsis;
        white-space: nowrap;
    }
    .espace{margin-top:80px;}
    .espace1{margin-top:25px;}
    .entete ul{
        list-style:none;
    }
    .pan_title {
        font-family: 'Lobster', cursive;
        font-size: 25px;
        font-weight: 15px;
        color:  #009900;
    }
    .pce{
        font-family: 'Lobster', cursive;
        font-size: 15px;
        font-weight: 105px;
        color:  #000;}.titrep1{
        margin-left:40px;
    }
    .col-sm-offset-9 {
        margin-left: 65%;
    }
    .col-sm-offset-2 {
        margin-left: 16.66666667%;
    }
    .col-sm-offset-8 {
        margin-left: 66.66666667%;
    }
</style>
<div>

    <div class="">
        <div class="entete">
            <ul class="devise">
                <li>BANQUE CENTRALE DE MAURITANIE</li>
                <li>DIRECTION GENERALE DE </li>
                <li>L'ADMINISTRATION ET DE LA LOGISTIQUE</li>
                <li>DIRECTION DES AFFAIRES SOCIALES</li>

            </ul>
        </div>
        <div class="espace1"></div>
        <div class="col-sm-offset-9">Nouakchott le {{piece.date_soin.day}}/{{piece.date_soin.month}}/{{piece.date_soin.year}}</div>
        <div class="espace1"></div>
        <div class="titrep">
            <span class="col-sm-offset-2 pce">FICHE DE CIRCULATION PRISE EN CHARGE</span>
        </div>

        <div class="espace"></div>
        <div class="">
            <dl class="dl-horizontal">
                <dt>Nom & Penom :</dt>
                <dd>{{ piece.Nom_prenom }}</dd>
            </dl>
            <div class="espace1"></div>

            <dl class="dl-horizontal">
                <dt>Id du patient :</dt>
                <dd>{{ piece.id_patient}}</dd>
            </dl>
            <div class="espace1"></div>
            <dl class="dl-horizontal">
                <dt>Matricule :</dt>
                <dd>{{piece.Matricule.matricule}}</dd>
            </dl>
            <div class="espace1"></div>
            <dl class="dl-horizontal">
                <dt>Nat medical :</dt>
                <dd>{{ piece.description }}</dd>
            </dl>
            <div class="espace1"></div>
            <dl class="dl-horizontal">
                <dt>Stru. sanitaire :</dt>
                <dd>{{ piece.clinique }}</dd>
            </dl>
            <div class="espace1"></div>
            {% if piece.chef_sec == "" %}
                <dl class="dl-horizontal">
                    <dt>A. chef section interne :</dt>
                    <dd>En attente de decision</dd>
                </dl>
                <div class="espace1"></div>
            {% else%}
                <dl class="dl-horizontal">
                    <dt>A. chef section interne :</dt>
                    <dd>{{ piece.chef_sec }}</dd>
                </dl>
                <div class="espace1"></div>
            {% endif%}
            {% if piece.chef_serv == ""%}
                <dl class="dl-horizontal">
                    <dt>A. chef service :</dt>
                    <dd>En attente de decision</dd>
                </dl>
                <div class="espace1"></div>
            {% else %}
                <dl class="dl-horizontal">
                    <dt>A. chef service :</dt>
                    <dd>{{ piece.chef_serv }}</dd>
                </dl>
                <div class="espace1"></div>
            {% endif%}
            {% if piece.dir == ""%}
                <dl class="dl-horizontal">
                    <dt>Decision directeur :</dt>
                    <dd>En attente de decision</dd>
                </dl>
            {% else %}
                <dl class="dl-horizontal">
                    <dt>Decision directeur :</dt>
                    <dd>{{ piece.dir }}</dd>
                </dl>
            {% endif%}




        </div>
    </div>
</div>

ser_medical/templates/ser_medical/form.html
{% extends "base.html" %}

{% block content %}
{% load staticfiles %}
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script src="{% static 'core/js/form_js.js' %}" type="text/javascript"></script>
<script type="text/javascript">
    // Definition of global variables for javascript context
    var contact_url = '{% url 'contact' %}';
</script></head>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <p>&nbsp;</p>
    <form id="contact" action="{% url 'contact' %}" method="post" class="niceform" novalidate>{% csrf_token %}
        <dl>
            <dt>{{ form.name.label_tag }} :</dt>
            <dd>{{ form.name }}</dd>
            <dd>{{ form.name.errors }}</dd>
        </dl>
        <dl>
            <dt>{{ form.firstname.label_tag }} :</dt>
            <dd>{{ form.firstname }}</dd>
            <dd>{{ form.firstname.errors }}</dd>
        </dl>
        <dl>
            <dt>{{ form.email.label_tag }} :</dt>
            <dd>{{ form.email }}</dd>
            <dd>{{ form.email.errors }}</dd>
        </dl>
        <dl>
            <dt>{{ form.password.label_tag }} :</dt>
            <dd>{{ form.password }}</dd>
            <dd>{{ form.password.errors }}</dd>
        </dl>
        <dl>
            <dt>{{ form.message.label_tag }} :</dt>
            <dd>{{ form.message }}</dd>
            <dd>{{ form.message.errors }}</dd>
        </dl>
        <div class="break">
            <input type="submit" value="Submit" />
        </div>
    </form>
{% endblock%}

ser_medical/templates/ser_medical/info_charge.html
<style>
    body {
      background-color: #f7f7f7;
    }
    .ctnu{
margin-left:20px;
}
    .dl-horizontal dd {
    margin-left: 180px;
  }.dl-horizontal dt {
    float: left;
    width: 160px;
    overflow: hidden;
    clear: left;
    text-align: right;
    text-overflow: ellipsis;
    white-space: nowrap;
  }
    .espace{margin-top:40px;}
.espace1{margin-top:15px;}
    .entete ul{
    list-style:none;
    }
    .pan_title {
    font-family: 'Lobster', cursive;
    font-size: 25px;
    font-weight: 15px;
    color:  #009900;
}.pce{
font-family: 'Lobster', cursive;
    font-size: 15px;
    font-weight: 105px;
    color:  #000;}.titrep1{
margin-left:40px;
}.col-sm-offset-9 {
    margin-left: 65%;
  }.col-sm-offset-2 {
    margin-left: 16.66666667%;
  }
  .col-sm-offset-8 {
    margin-left: 66.66666667%;
  }
  </style>
<div id="_{{piece.id}}_p2" class="modal fade" role="dialog" aria-labelledby="_{{piece.id}}_title" aria-hidden="true">
    <div>

        <div class="entete">
            <ul class="devise">
                <li>BANQUE CENTRALE DE MAURITANIE</li>
                <li>DIRECTION DES AFFAIRES SOCIALES</li>
                <li>SERVICE MEDICAL</li>
            </ul>
        </div>
        <div class="espace"></div>
        <div class="col-sm-offset-9">Nouakchott le {{piece.date_soin.date}}</div>
        <div class="espace"></div>
        <div class="titrep row">
            <span class="titrep1">N____{{piece.id}}______/</span>
            <span class="col-sm-offset-2 pce">PRISE EN CHARGE</span>
        </div>
        <div class="espace"></div>
        <div class="ctnu">
        Nous soussignes, Banque Centrale de Mauritanie, nous nous engageons à prendre en charge<br>
        à hauteur de 100% frais...............................................et Epreuve d’effort de
        ………………………………….<br><div class="espace"></div>

        Cadre de notre Institution.<br><div class="espace"></div>
        <span class="ctnu2">Envoyé ce jour auprès du : {{piece.clinique.libele}}<br></span>
        <div class="espace"></div>
        La presentation du livret familial est exigee<br>
        <div class="espace"></div>
        <span class="ctnuPr"> La duree de validité de cette prise en charge est d’un mois
    à partir de la date de signature.
    <br>
        <div class="espace"></div>
        Toute prise en charge non utilisée dans le délai susmentionné
    doit être impérativement retournée à l’administration de la banque
    </span>

        </div>
        <div class="espace"></div>
        <div class="pce col-sm-offset-8">
            LE DIRECTEUR-ADJOINT
        </div>
        <div class="espace1"></div>
        <div class="pce col-sm-offset-8">BOCAR D. DIAGANA</div>
    </div>
</div>

ser_medical/templates/ser_medical/liste_cliniques.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_medical/js/listKlinik.js' %}" type="text/javascript"></script>
{% endblock %}
<div >
    <table class="table table-striped table-hover">
        {% if cliniques%}
        <caption><span class="pan_title">Liste des Cliniques en convention avec la BCM</span></caption>
            <thead>
                <tr class=" col-lg-1">
                    <th>CODE</th>
                    <th>LIBELE</th>
                    <th>PAYS</th>
                </tr>
            </thead>
        {%endif%}
        <tbody>
            {% for cl in cliniques %}
            <tr>
                <td >{{cl.code}}</td>
                <td >{{cl.libele}}</td>
                <td >{{cl.pays}}</td>
                <td><a href="#" data-toggle="tooltip" title="Editer" class="icon-1" ></a></td>
            </tr>
            {% empty %}
            <tr><td>PAS DE CLINIQUE ENREGISTRER</td></tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="col-lg-offset-3" id="page_navigation2"> </div>
</div>

ser_medical/templates/ser_medical/nouv_charge_med.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_medical/js/pCharge.js' %}" type="text/javascript"></script>
{% endblock %}
<div class="panel-heading" id="pan_title">Nouvelle Prise en Charge Medicale</div>
<form id="charge_id" action="{% url 'addCharge' %}" method="post" class="niceform panel-body " novalidate enctype="multipart/form-data">
        {% csrf_token %}
    <fieldset class="well">
            <legend></legend>
        <div class="row">
            <div class="col-sm-6">
            <dl>
                <dt>Nom & Penom</dt>
                <dd>{{ form.Nom_prenom }}</dd>
                <dd>{{ form.Nom_prenom.errors }}</dd>
            </dl>

            <dl>
                <dt>Identification du patient</dt>
                <dd>{{ form.id_patient}}</dd>
                <dd>{{ form.id_patient.errors }}</dd>
            </dl>
            <dl>
                <dt>Matricule</dt>
                <dd>{{ form.matricule}}<img width="75" height="50" src="{% static 'ser_medical/images/blueeye.png'%}"></dd>


                <!--<input id="id_matricule" name="matricule" type="number" required="">-->
            </dl>
                <!--<input id="id_montant" name="montant" type="number" required="" class="errr">-->

            <dl>
                <dt>Nature de l'acte medical</dt>
                <dd>{{ form.description }}</dd>
                <dd>{{ form.description.errors }}</dd>
            </dl></div>
<div class="col-sm-5">
            <dl>
                <dt>Structure sanitaire</dt>
                <dd>{{ form.clinique }}</dd>
                <dd>{{ form.clinique.errors }}</dd>
            </dl>

            <dl>
                <dt>Avis chef section interne</dt>
                <dd>
                    <select id="id_chef_sec" name="chef_sec" required="">
                        <option value="" selected="selected">----------------</option>
                        <option value="defavorable">defavorable</option>
                        <option value="favorable">favorable</option>
                    </select>
                </dd>
            </dl>

            </div>



            <div class="">
                <input class="btn btn-success" type="submit" value="Ajouter" />
            </div>
        </div>
        </fieldset>

</form>
<div class="row"><section id="employe"></section></div>

ser_medical/templates/ser_medical/nouv_ordonnance.html
{% load static %}
{% block JheadScript %}
    <script src="{% static 'ser_medical/js/ajoutOrdon.js' %}" type="text/javascript"></script>
{% endblock %}
<div class="panel-heading pan_title">Nouvelle Ordonnance</div>
<form id="ajoutrForm" action="{% url 'addOrdonnance' %}" method="post" class="niceform panel-body" novalidate enctype="multipart/form-data">{% csrf_token %}
    <fieldset id="" class="ctn1">
        <legend></legend>
        <div class="col-sm-7">
            <dl class="dl-horizontal">
                <dt>{{ form.reference.label_tag }}</dt>
                <dd>{{ form.reference }}</dd>
                <dd>{{ form.reference.errors }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>{{ form.type.label_tag }}</dt>
                <dd>{{ form.type }}</dd>
                <dd>{{ form.type.errors }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>{{ form.montant.label_tag }}</dt>
                <dd>{{ form.montant }}</dd>
                <dd>{{ form.montant.errors }}</dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>Matricule</dt>
                <dd><input id="id_matricule" min="0" name="matricule" type="number" required=""></dd>
                <dd></dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>{{ form.assure.label_tag }}</dt>
                <dd>{{ form.assure }}</dd>
                <dd>{{ form.assure.errors }}</dd>
            </dl>
            <div class="row col-sm-offset-3 col-sm-5">
                <input class="btn btn-success" type="submit" value="Submit" />
            </div>
        </div>
        <div class="col-sm-5"><section id="employe"></section></div>
    </fieldset>

</form>